#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source "$(brew --prefix)/etc/profile.d/z.sh"

autoload -U +X bashcompinit && bashcompinit

# For work machines only.
complete -o nospace -C /usr/local/bin/terraform terraform
